SCHEDULE_CANCELLED = 'CANCELLED'
SCHEDULE_SCHEDULED = 'SCHEDULED'
SCHEDULE_MODIFIED = 'MODIFIED'
SCHEDULE_MODIFIED_WITHOUT_RANGE_VALIDATION = 'MODIFIED_WITHOUT_RANGE_VALIDATION'
SCHEDULED_ABSENT = 'ABSENT'
SCHEDULED_PRESENT = 'PRESENT'
CHANGE_TICKET_TYPE_CANCEL = 'CANCEL'
CHANGE_TICKET_TYPE_MODIFY = 'MODIFY'
CHANGE_FROM_USER = 'USER'
CHANGE_FROM_TRAINER = 'TRAINER'
CHANGE_TICKET_STATUS_WAITING = 'WAITING'
CHANGE_TICKET_STATUS_APPROVED = 'APPROVED'
CHANGE_TICKET_STATUS_REJECTED = 'REJECTED'
CHANGE_TICKET_STATUS_CANCELED = 'CANCELED'
DATETIMEFORMAT = '%Y-%m-%d %H:%M:%S'
DATEFORMAT = '%Y-%m-%d'
TIMEFORMAT = '%H:%M'
SCHEDULE_TYPE_MONTH = "MONTH"
SCHEDULE_TYPE_DAY = "DAY"
SCHEDULE_TYPE_WEEK = "WEEK"


class Const:
    SCHEDULE_CANCELLED = 'CANCELLED'
    SCHEDULE_SCHEDULED = 'SCHEDULED'
    SCHEDULE_MODIFIED = 'MODIFIED'
    SCHEDULED_ABSENT = 'ABSENT'
    SCHEDULED_PRESENT = 'PRESENT'
    CHANGE_TICKET_TYPE_CANCEL = 'CANCEL'
    CHANGE_TICKET_TYPE_MODIFY = 'MODIFY'
    CHANGE_FROM_USER = 'USER'
    CHANGE_FROM_TRAINER = 'TRAINER'
    CHANGE_TICKET_STATUS_WAITING = 'WAITING'
    CHANGE_TICKET_STATUS_APPROVED = 'APPROVED'
    CHANGE_TICKET_STATUS_REJECTED = 'REJECTED'
    CHANGE_TICKET_STATUS_CANCELED = 'CANCELED'
    CHANGE_TICKET_STATUS_RESOLVED = 'RESOLVED'
    DATETIMEFORMAT = '%Y-%m-%d %H:%M:%S'
    DATEFORMAT = '%Y-%m-%d'
    TIMEFORMAT = '%H:%M'
    SCHEDULE_TYPE_MONTH = "MONTH"
    SCHEDULE_TYPE_DAY = "DAY"
    SCHEDULE_TYPE_WEEK = "WEEK"


const = Const()
